spring:
  application:
    name: wallet
  profiles:
    default: sample
    group:
      dev:
        - wallet
        - logging
        - spring-docs
        - database
        - tas
        - blockchain
      sample:
        - logging
        - spring-docs
        - database-sample
        - wallet
        - tas

  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false

server:
  port: 8095

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
      base-path: "/wallet/health"
  endpoint:
    health:
      show-details: "always"